### ISSUE TITLE
Automatic playback 

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#108]
In the video player, it seems you have introduced autoplay next setting but the label says "automatic playback" which I assume means autostart current video.

It would just need a label change. Thats all.

**Comment by test2a** [comment]
![Screenshot_20201122-101616](https://user-images.githubusercontent.com/39449563/99896132-a1c8ed80-2cb3-11eb-8956-c3200b134bac.png)

**Comment by stom79** [comment]
It's an error, it's for playing automatically next videos
