### ISSUE TITLE
app crash on notifciation containing mentions

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#113]
### Issue

i got the latest 1.8 from playstore and the app is still crashing on notifications that contain a mention. 
in the screenshot i have 4 comments from jeena and one from wonderingdane. all crash the app. the published new video works just fine
![Screenshot_20201123-215116](https://user-images.githubusercontent.com/39449563/99987306-4f342200-2dd6-11eb-9ae7-67401c80b1f6.png)

also the message is somewhat wrong. it is saying "commented on your video" while the web version says "mentioned you in the following video"

i know the message has to be truncated and all, how about we say in respect of videos which are not ours, "abc mentioned you in a comment on xyz"

![Screenshot_20201123_215345](https://user-images.githubusercontent.com/39449563/99987415-6f63e100-2dd6-11eb-8e09-1a2d868f3ea2.png)

### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by test2a** [comment]
this was earlier fixed apparently but i think the bugs still persist

**Comment by test2a** [comment]
![recording_20201124_111214](https://user-images.githubusercontent.com/39449563/100053507-32cfce00-2e46-11eb-8506-0f1f9b7650f2.gif)

**Comment by stom79** [comment]
Yes. It's fixed

**Comment by test2a** [comment]
The play store version 1.8 is having this issue on two accounts.

**Comment by stom79** [comment]
It will be in 1.8.1 ;)

**Comment by test2a** [comment]
Great. 1.8 has some random crashes which I have been unable to replicate. Will try to investigate further
