### ISSUE TITLE
Unable to access some channels or subscribe to accounts

### ISSUE THREAD

**Issue by Silmathoron** [stom79/TubeLab#115]
### Issue
Using TubeLab 1.8.0 (but since 1.6 at least and probably from the start) I am unable to access channels and accounts from some servers.

Same problem occurs for some channels to which I subscribed on the web but cannot but cannot see the video in my feed.

These include, for instance:
* MonsieurPhi
* TILVids accounts

Might be related to #58? (issue was not clear to me)

### Steps for reproducing the issue

For the account problem

1. Go to SepiaSearch
2. Type in "monsieurphi"
3. Tap on the avatar of [monsieurphi@video.antopie.org](https://video.antopie.org/video-channels/monsieurphi)
4. See ``{error: "Video channel not found"}``
5. Click on subscribe and nothing happens

For the empty videos on subscribed channels

1. Go to subscription feed tab
2. Tap Fermilab icon
3. See empty list of videos even though their latest video is actually listed on the "all videos" list of my subscriptions

---

Instance: [Ploud FR](https://video.ploud.fr/).

- [x] TubeLab
- [ ] TubeAcad

Version of TubeLab: 1.8.0

Android version: Lineage (Microg build) 17.1

**Comment by Silmathoron** [comment]
Actually, I finally realized that I had not tried that from the internet and it turns out that I can apparently not access video.antopie.org from ploud on the web either, so that issue probably is not related to TubeLab... any idea how I may solve this or where I should report it?

**Comment by test2a** [comment]
yeah... i was about to write the same thing. it should probably be reported to the instance of https://video.antopie.org it is probably some permissions issue on the server side

**Comment by test2a** [comment]
here.
watch this video. this is relevant for your needs
https://devtube.dev-wiki.de/videos/watch/51a189cf-3372-4f97-9ff7-b5982dce4c9e
so what you do is, open video.antopie.org , search for a channel that you want to subscribe, click on any video and copy the url. then in your own instance, ploud, paste that url in the search bar. the video should play. then just click subscribe.
it is janky and complicated but you have to do it just once to understand the procedure

**Comment by Silmathoron** [comment]
> watch this video. this is relevant for your needs
> https://tube.jeena.net/videos/watch/51a189cf-3372-4f97-9ff7-b5982dce4c9e

The video you provided is not working for me, I get `` Sorry, we couldn't find the page you were looking for. ``
And using the trick you propose does not work: the local server does not find the video even using the URL.

**Comment by test2a** [comment]
i recorded my screen. this video link is working for me. 

are you logged into your instance ploud while trying this? i tried to add a few videos to peertube2.cpy.re without logging in and it failed but for my instance, after logging in it works.
 i am not sure why this issue is though. i will investigate some more
![recording_20201127_155309](https://user-images.githubusercontent.com/39449563/100439020-f8299800-30c8-11eb-9bef-35fcfa025e8f.gif)

**Comment by test2a** [comment]
here.
https://github.com/stom79/TubeLab/issues/65#issuecomment-731574743
https://tube.ouahpiti.info

add this account to your app and try. we need to isolate the problem which might be due to some configuration issue in your ploud instance. you can also try to use the desktop and try from there, just to avoid app specific bugs

**Comment by stom79** [comment]
So should it be closed?

**Comment by test2a** [comment]
@Silmathoron did you try with another instance or another video/channel ?

**Comment by Silmathoron** [comment]
@stom79 the issue with MonsieurPhi seems to be specific, so seeing a channel/account should work.
However, the issue of empty video list still remains for accounts like [Fermilab ](https://tilvids.com/video-channels/fermilab/videos) which works otherwise fine (I can actually play their videos if I go directly on one).

**Comment by stom79** [comment]
Yes, I confirm that I planned to fix that bug :)

**Comment by test2a** [comment]
Yes. This is what I mentioned here  https://github.com/stom79/TubeLab/issues/65#issuecomment-732278231

Is this what you are referring to?

I searched for fermilab on sepiasearch and I reached the channel just fine. Then the video listing was also fine. All videos were listed.
Then if I click on subscribe which actually takes 2 clicks now, the videos in subscription show up but clicking on icon says no video.

**Comment by stom79** [comment]
OK. It's fixed. But for information. The web app acts as TubeLab did (it doesn't display videos when filtering them for accounts coming from a remote instance that is not federated with the original one). I added a trick that now allows to filter these accounts.

**Comment by Silmathoron** [comment]
OK, I did not know that, thanks a lot for all you effort!
