### ISSUE TITLE
[Feature] Chromecast support

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#123]
This is a longshot but vlc has a Foss implementation of Chromecast support and it would be nice to have that in tubelab as well.

I don't use a Chromecast or any casting myself but there are a lot of people who do so it would be a good addition for the overall peertube ecosystem

**Comment by test2a** [comment]
eh. there does seem to be only one library supporting this 
https://github.com/vitalidze/chromecast-java-api-v2

maybe you could check if this works or not? i am not sure

**Comment by stom79** [comment]
Well at least it detects the chromecast but I get a timeout when streaming it :thinking:

**Comment by stom79** [comment]
It will be in the next release. It works without play services but it's in beta. There is a custom player for play/pause. I still need to fix some edge effects but that's working.
