### ISSUE TITLE
Home area bug

### ISSUE THREAD

**Issue by Kohoshi12** [stom79/TubeLab#124]
### Issue

The home area, apparently to show local videos of an instance, is not showing any new videos.

### Steps for reproducing the issue
 Go to the home area and look at the release time of the videos.

---

Instance: https://tube.privacytools.io/

- [x] TubeLab
- [ ] TubeAcad

Version of TubeLab: 1.9.0

Android version: 10

**Comment by test2a** [comment]
what tab are you talking about. 
there are
* discover
* subscriptions
* trending
* recently added
* local

**Comment by test2a** [comment]
there is no tab named home afaik

**Comment by Kohoshi12** [comment]
No, there's an area called Home, but in the same space writed Local. This area is different from the others.

**Comment by Kohoshi12** [comment]
![Imagepipe_0](https://user-images.githubusercontent.com/74657968/100834843-f2102e80-34af-11eb-90f9-e54647aece9b.jpg)

**Comment by test2a** [comment]
oh. for me it says local.
![Screenshot_20201202-113720](https://user-images.githubusercontent.com/39449563/100835046-f4b05b00-3492-11eb-8af2-c3688b2fbfa1.png)

oh. it must be the logged in /not loggged in mode. wait i will check

**Comment by test2a** [comment]
ah yes. without logging in it says home. got it.

**Comment by test2a** [comment]
yes. i concur. there is a bug with almost all tabs except discover

**Comment by test2a** [comment]
ok. can you check https://tilvids.com/ on the app and browser for me please? it is a smaller instance and finding bugs easier. i just found out home button is copying recently added  and recently added only shows videos from over 15 hours ago. any video in the last 15 hours is not shown

**Comment by Kohoshi12** [comment]
The problem with tilvids.com is the same to me as you described. I think it's good to add the subscriptions tab as the sites have.

**Comment by test2a** [comment]
also there should be no "home" tab in unauthenticated mode. 
also, subscriptions only show when you are logged in so without logging in, its fine

**Comment by Kohoshi12** [comment]
I hope I found a bug.

**Comment by test2a** [comment]
yeah @Kohoshi12 the only way to improve the app is to test test test and find issues so that @stom79 can fix them. hehe . i am also not a developer. i just report bugs here and the app has immensely improved since 1.5 due to that
