### ISSUE TITLE
[enhancement] recognise "start=" in url and play video from that start point

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#133]
### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by stom79** [comment]
It should... Could you share the original URL where it fails? I suspect an encoded char like the question mark. If so, it will be an easy fix.

**Comment by test2a** [comment]
https://peertube2.cpy.re/videos/watch/9c9de5e8-0a1e-484a-b099-e80766180a6d?start=49s

https://peertube2.cpy.re/videos/watch/338c6565-ae8b-4367-81d1-604bdc1afa4c?start=7m50s
or any link from say peertube2.cpy.re as that is the most up to date instance. 

i tried to share this link on telegram and clicking it, it opens correctly but video starts from the start, not from the time in the url. same for putting the url in search. it plays from start

**Comment by stom79** [comment]
Does not seem to be an issue with the regex https://regex101.com/r/f1zyJp/1/

**Comment by test2a** [comment]
Nah. The video is playing OK. That is not the problem


Video is NOT recognising the start time. It is ignoring that

**Comment by stom79** [comment]
Yes, but the regex correctly extracts the time

**Comment by test2a** [comment]
Is the player accepting that time? All links I have tested the videos play from the start only.

**Comment by stom79** [comment]
OK. It's fixed. I broke this feature recently. Also, I added the support when searching.
