### ISSUE TITLE
[bug][feature] user with no upload permission should not show upload button-doing so crashes app

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#134]
### Issue

i just created an instance on gitpod and created a user with no upload permission. inputting that in app allows me to open the upload page but the app crashes.
the app should check if user has uploads disabled, if yes, uploads should be hidden...

the app currently crashes because it tries to upload but there are no permissions 

### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by stom79** [comment]
What's the instance URL so I can check?

**Comment by test2a** [comment]
Oh. I created a gitpod.io

You can spin one up for free with peertube

https://3000-e320c2a5-c811-4cbf-bf62-48b615aacfbe.ws-us03.gitpod.io/

User:tt
Pass:testtest

Here. This user I set up without upload permission

**Comment by stom79** [comment]
@test2a thanks. Fixed.

**Comment by test2a** [comment]
@stom79 so many thanks
