### ISSUE TITLE
[bug] popup player has grey overlay

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#137]
![Screenshot_20201206-202602 (1)](https://user-images.githubusercontent.com/39449563/101287294-6979f100-3815-11eb-8e49-d2de2facf101.png)
### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by stom79** [comment]
That's the wanted behavior to see buttons in controller when zooming it out.
