### ISSUE TITLE
[feature] show total downloaded/uploaded in video player page somewhere

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#138]
### Issue

it could be in a modal like we show video license and information but this information is very important for users education. i just tried to view a live stream
https://live.canard.tube/videos/watch/5e7b916e-c5b5-4996-a970-cf106967fe32
and switched to torrent mode and there was no performance penalty i can find. only the fullscreen bug i found as i have already mentioned. the torrent mode should tell me how much data was downloaded from servers, peers and how much i shared myself. just like the website. i think you just have to pull those figures, the work is already done

### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by test2a** [comment]
maybe even in the gear icon menu.that would work too i guess

**Comment by stom79** [comment]
Yes, that are interesting information. I will try to offer a way to display that stats.

**Comment by test2a** [comment]
https://live.canard.tube/videos/watch/5e7b916e-c5b5-4996-a970-cf106967fe32

i am using the torrent mode right now and i think because live are shared, it would be nice if we switched to torrent mode for live because that would help in sharing bandwidth. normal mode is just leech mode. 

how about checking if video is live and switching to torrent? ask the user for permission the first time? in settings?
