### ISSUE TITLE
[bug] popup player image is stretched

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#140]
![Screenshot_20201206-230338](https://user-images.githubusercontent.com/39449563/101287665-a7781480-3817-11eb-8a02-0423f66e0ae9.png)
### Issue

the image is streched to just one corner of the video. it should show the full view even in popup mode

### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by test2a** [comment]
OK. This only happens sometimes. Closing the video and starting again fixes it.

**Comment by stom79** [comment]
I don't have control on that (picture in picture mode), but updating a lib could bring bugs like fixes. I will follow that.

**Comment by test2a** [comment]
it also happens if i go in and out of fullscreen and popup mode with the normal player

i am not able to reproduce it now but i saw it earlier

**Comment by stom79** [comment]
I will wait lib upgrade as I have no control on that point.
