### ISSUE TITLE
[Bug] remote instances issue in subscriptions

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#143]
Subscriptions have a weird bug I am seeing lately. Firstly all subscribed channels which are remote show no videos to display, secondly, their videos do show in the subscription list. Just not when we click on profile.
Third, some remote channels do not show its videos in the list. Only when I click on its image at the top. Those videos show. If I click on all, these videos are gone.

**Comment by stom79** [comment]
> Third, some remote channels do not show its videos in the list. Only when I click on its image at the top. Those videos show. If I click on all, these videos are gone.

I don't get this one.

**Comment by stom79** [comment]
I can't reproduce the first point for all videos. The only channel affected by this bug is a remote channel publishing NSFW videos.

**Comment by test2a** [comment]
can you use the login credentials of ouahpiti i sent last time. that would get you up to speed and share the same issues
i am sending you a screen recording in the meantime

**Comment by test2a** [comment]
![recording_20201213_133225_1](https://user-images.githubusercontent.com/39449563/102007683-2a85f700-3d51-11eb-8de4-3422492d01a7.gif)

**Comment by test2a** [comment]
watch the video. the fediversal channel shows videos in all but if i cliclk on its image, no videos

second, the first icon at top, luke smith. his videos dont even show up in the list or when opening his profile. only when clicking his icon at top, all videos show

**Comment by stom79** [comment]
OK. I added the fix for remote subscriptions.

**Comment by stom79** [comment]
It also fixes avatars not loaded.

**Comment by stom79** [comment]
I also fixed the horizontal view that had its pagination broken, thus only first pictures were loaded and not all subscribed channels.

**Comment by stom79** [comment]
I will publish that fix on 1.10.1 because I also have a crash bug when creating a playlist.
