### ISSUE TITLE
[Bug] account not found - When not authenticated

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#145]
https://diode.zone/videos/watch/25e90ea7-a0cc-47c3-b59a-c1e2a096bbe8

This video works fine in the app. The channel also works but if I click on account in the sidebar, it says account not found but 

https://diode.zone/accounts/kzimmermann/video-channels

This page opens correctly on website.

**Comment by test2a** [comment]
![Screenshot_20201215-201858](https://user-images.githubusercontent.com/39449563/102230821-52bd5380-3f13-11eb-9a2a-1906fda74b42.png)

**Comment by test2a** [comment]
it shows the videos on the tab but no channels and this error

**Comment by test2a** [comment]
Yes.. I updated to 1.10.1 from play store and this bug persists.

Same for few others including the remote channels one. Some channels now show correctly but not all. Also, some entries are missing in subscriptions tab.

**Comment by stom79** [comment]
I can't reproduce that.

**Comment by test2a** [comment]
Yes. Click on URL to open in tubelab. 
Then click on image.
Then in sidebar click on account. 
It says error

**Comment by stom79** [comment]
I really can't reproduce it :-\

**Comment by stom79** [comment]
OK. That happens when being logging out

**Comment by test2a** [comment]
It happens to me when I am logged in... sigh
