### ISSUE TITLE
[bug] do not list in display sensitive content is not working

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#152]
### Issue

do not list setting on web hides the videos. in the app this setting is same as "display". blur works as expected but not "do not list"

first screenshot is after setting to blur and second one is after setting to do not list. on web  the sensitive video gets hidden in local
### Steps for reproducing the issue
![Screenshot_20201217-223543](https://user-images.githubusercontent.com/39449563/102519483-89809e80-40b8-11eb-8dc6-0f3b73f95f38.png)
![Screenshot_20201217-223555](https://user-images.githubusercontent.com/39449563/102519491-8be2f880-40b8-11eb-9277-92aac8ec22ef.png)

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by stom79** [comment]
OK. I thought filter was made on server side.

**Comment by stom79** [comment]
My bad, I forgot to apply for not authenticated accounts. That's fixed.
