### ISSUE TITLE
[Feature] annotations and watermarks

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#154]
https://peervideo.ru/videos/watch/7a546a08-332e-4094-b9bb-a23a1a7369ea

This instance for example peervideo.ru injects a watermark on its own videos.
You can see this in the top right of video player. It is absent in app

**Comment by test2a** [comment]
yes. confirmed no annotations are shown

**Comment by stom79** [comment]
I will check that elements in the API. But what's the purpose of watermarks that aren't embedded into videos? I mean how to add it when downloading.
Currently the link is in 404, I might have not clearly understood the problem.

**Comment by test2a** [comment]
https://peervideo.ru/videos/watch/ce0d29d9-a727-46c8-af8e-e34a4482a96b

So plugins can allow user to introduce stuff into video player. Like this website uses a watermark at top right corner.

Peervideo.ru

**Comment by test2a** [comment]
Accessibility. Think of it like how subtitles are separate from video file.
A creator can add links, HTML, logos  (like TV channel symbols) to make their content /instant distinct. This adds value to the software as a whole.

**Comment by stom79** [comment]
I don't know... Bringing support to plugins is not a priority IMO.

**Comment by stom79** [comment]
OK. Watermark through plugins will be supported in the next release.
