### ISSUE TITLE
[Question] how to see if torrent mode works or not

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#155]
Live is here and I have observed some things. 
The website has a latency of around 40 seconds for me on peervideo.ru.

On the phone, it is 10 seconds less. I found on framacolibri discourse blog, chocobozz say tubelab does not use p2p and does not introduce latency to help with torrenting.

Can you investigate that ?

If I am using the app in torrent mode, am I a peer uploading and downloading from others or not ?

**Comment by stom79** [comment]
I disagree. Fedilab doesn't use p2p by default would be more correct.
