### ISSUE TITLE
[bug] livestream crashes app and says oops

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#156]
### Issue

https://peertube3.cpy.re/videos/watch/fb1bc38d-b2d9-4a34-b639-81d644007e55

this live used to work on 1.10.1 but updating to 10.2, if i am logged out, it crashes app and if logged in, it says oops and does not play the video/live

i have tried multiple times to uninstall and install the app but this link is not working

### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by test2a** [comment]
![Screenshot_20201223-130505](https://user-images.githubusercontent.com/39449563/102971633-b7823a80-451f-11eb-9ba4-90ad6330b661.png)
this also does not have live badge

**Comment by test2a** [comment]
https://github.com/Chocobozzz/PeerTube/issues/3511

Video from this issue is also crashing the app.

**Comment by stom79** [comment]
It's fixed when solving #154 (I noticed that I was trying to increase the view count before getting the video ID).

**Comment by test2a** [comment]
Just updated to 1.11 and this video says live not started but the web version is playing just fine.
This is if I search with URL. I have subscribed to this channel and clicking there says oops

@stom79

**Comment by test2a** [comment]
![Screenshot_20210105-093723](https://user-images.githubusercontent.com/39449563/103615817-43995680-4f51-11eb-88d9-0afce0ef1074.png)

**Comment by test2a** [comment]
only lives have this issue as normal videos work fine

**Comment by stom79** [comment]
Do you know video URL where the live didn't start? I fixed the previous issue.

**Comment by stom79** [comment]
for tests: https://framadrive.org/s/A78Kwg86nXdbZMZ

**Comment by test2a** [comment]
@stom79 also found out the live only plays for 2-3 seconds and ends while in the browser the live is working as normal.

Also this happens with normal mode. While torrent and magnet refuses to play

**Comment by stom79** [comment]
>This live URL works in normal mode just fine now 

>also found out the live only plays for 2-3 seconds and ends while in the browser the live is working as normal.
>Also this happens with normal mode. 

So it does'work with normal mode too? Did you grant write access to the app?

**Comment by test2a** [comment]
note: i am using the framadrive apk you send the other day. 
also, it did NOT ask me for storage permission. i enabled that but torrent mode still says same error as in the video
normal mode plays some old cached version i think. 
let me try clearing cache
https://user-images.githubusercontent.com/39449563/104008650-b4e63d00-51cf-11eb-84cf-724493d53e2a.mp4

**Comment by test2a** [comment]
ok. i cleared cache and in normal mode it only plays for 10 seconds and stops.

**Comment by stom79** [comment]
It's due to cache feature enabled in settings. If you disabled it, that should work. I will automatically remove it for lives.

**Comment by test2a** [comment]
OK. That did work for normal mode. Torrent still shows oops

**Comment by stom79** [comment]
I have no torrent information returned for lives. I should force normal mode.

**Comment by test2a** [comment]
Uh.... how does this live show peers? It *should* torrent because of p2p ?  

OK. If you do normal mode, would it enter the p2p sharing?

**Comment by stom79** [comment]
I meant, I don't get the info via the API. I have to check for entering in p2p, I think it's possible by initializing p2p and set the cache for videos in the same directory. 

But I would prefer that these info get returned by the API like for other videos.

PS: Magnet currently doesn't work because I target Android 11 and the java lib has some issues due to write access. That should be fixed soon, I hope.

**Comment by stom79** [comment]
You can try this one: https://framadrive.org/s/A78Kwg86nXdbZMZ

**Comment by test2a** [comment]
@stom79 what to check with this update? I dont know what to look for

**Comment by stom79** [comment]
The problem of 10s playing when cache enabled. Also, watching a live with torrent fallback to normal mode.

**Comment by stom79** [comment]
It also fixes the issue when connecting a Pleroma account.

**Comment by test2a** [comment]
OK. Got it. I tested this with instance on 2.4 and that crashed like before but 3.0rc1 worked as expected.

On 3.0rc1, I saw download button which failed... that should be hidden

**Comment by stom79** [comment]
OK. Thanks. I might need to put support for older releases.
OK. For download button. I will remove it.

**Comment by test2a** [comment]
Cool. So excited for 3.0 release as well.

**Comment by stom79** [comment]
It's available. Just wait few days for that instances update it.
