### ISSUE TITLE
[bug] seekbar jumps around. the total time should be set at the start of video

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#157]
### Issue

![Screenshot_20201223-110337](https://user-images.githubusercontent.com/39449563/102963367-ea700280-450e-11eb-858d-8b4a3455ce28.png)
![Screenshot_20201223-110331](https://user-images.githubusercontent.com/39449563/102963389-f52a9780-450e-11eb-8f49-f46e95333768.png)
![Screenshot_20201223-110326](https://user-images.githubusercontent.com/39449563/102963399-fe1b6900-450e-11eb-893e-18792b86c8ee.png)

the seekbar at the start shows total time as 56 seconds. then at middle 1.25 and towards the end 2.35

### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by stom79** [comment]
Please, give a link to the video for tests

**Comment by test2a** [comment]
https://peervideo.ru/videos/watch/e0f8220e-80bb-46ec-aad0-372dde354d9b

Here you go

**Comment by stom79** [comment]
I will wait the update here: https://github.com/google/ExoPlayer/issues/5931
