### ISSUE TITLE
Language filter showing unselected languages

### ISSUE THREAD

**Issue by Bugsbane** [stom79/TubeLab#159]
### Issue
The app shows videos in languages other than the ones shown in the language filter setting. 

### Steps for reproducing the issue
1. Install TubeLab from Fdroid (currently version 1.10.1)
2. Go to app settings, click "language filter" and select English,  Spanish and Indonesian. 
3. Exit settings and restart app. Videos show in other languages (such as French) including the number 1 result: https://video.antopie.org/videos/watch/f3265270-838b-4e1f-bdfb-f4306502d611
If you click on this link and then click the "i" information button,  the language is set to French by the uploader.

---

Instance:
None,  or at least the default.  I didn't sign in or choose any instance. 

- [X] TubeLab
- [ ] TubeAcad

Version of TubeLab:
1.10.1 from Fdroid

Android version:
Android 10 on a Samsung SM-A515W (no Google account)

**Comment by test2a** [comment]
Can you tell me which tab you saw this video in ? Afaik peertube handles language filtering for certain tabs only.
Recently added, local, trending, most liked and search pages.

**Comment by stom79** [comment]
The languages should be synced with your account (if you are logged in). When restarting, are languages still selected in settings? Doesn't it happen on all timelines?
What happens if you don't restart the app and just pull-to-refresh on timelines once settings changed?

**Comment by Bugsbane** [comment]
I wasn't logged in, however I still expected language filtering to work without it. On quick inspection, it looks like this behaviour only happens on the "Discover" tab, although it happens even after closing, reopening and refreshing the timeline. The tabs other than "Discover" seem to work as expected though.

By the way, I also updated to 1.10.2 from Fdroid, which still has the same behaviour.

**Comment by stom79** [comment]
>I wasn't logged in, however I still expected language filtering to work without it. 

Yes it also uses device default language

**Comment by stom79** [comment]
The discover timeline doesn't allow to filter by language.

**Comment by Bugsbane** [comment]
Is that limitation from the Peertube server or Tubelab?

**Comment by test2a** [comment]
peertube from my tests

**Comment by stom79** [comment]
Yes, it's a limitation from Peertube API for the discover timeline.
