### ISSUE TITLE
[feature request] I hope it has an easier way to access notifications.

### ISSUE THREAD

**Issue by veer66** [stom79/TubeLab#160]
Maybe it is nice if I can check notifications in 1 or 0 tap.

**Comment by test2a** [comment]
Maybe a bell ? Like the web now shows a bell on the sidebar......

**Comment by veer66** [comment]
@test2a A bell must be great.

**Comment by stom79** [comment]
So moving account before playlist should solve that.

**Comment by test2a** [comment]
Yeah. That would work.. how about also having the profile icon  based on your account profile image of that size? Anyone who has configured that would see his own icon which could be configured as you have already solved that bit.

**Comment by stom79** [comment]
I can move that icon at the left of the top bar (before title) with the profile picture. That would be good?

**Comment by test2a** [comment]
How about you do that, give me a demo APk and I will try to assess it. But if we are doing right side sidebar, all controls should be on that side

**Comment by veer66** [comment]
> So moving account before playlist should solve that.

Then the app will require only one tap to see notifications. It is great!

Anyways, this is another thing. If the account icon show number of notifications similar to on a PeerTube web page, I think it will prevent me from forgetting to reply comments on my videos.
 
![image](https://user-images.githubusercontent.com/370688/103660683-79196080-4fa0-11eb-8a35-c0e8f3574369.png)

**Comment by veer66** [comment]
> I can move that icon at the left of the top bar (before title) with the profile picture. That would be good?

It is nice. I think it will look similar to the website.
