### ISSUE TITLE
Videos don't play when the screen is off

### ISSUE THREAD

**Issue by zcdunn** [stom79/TubeLab#162]
### Issue
When the _Screen lock_ setting is _on_, videos don't play after the screen is locked.

### Steps for reproducing the issue
1. Go to settings and make sure the _Screen lock_ setting is _on_. (Switch is orange and pushed to the right)
2. Start playing a video
3. Turn off the screen

---

Instance: https://betamax.video

- [x] TubeLab
- [ ] TubeAcad

Version of TubeLab: 1.10.2

Android version: 8.0.0 Moto g6

**Comment by stom79** [comment]
I will try to replicate that issue.

**Comment by test2a** [comment]
I have found a workaround but its not pretty. Keep the small player open or while watching the video, press back so that the popup player opens. Then close the screens a.d background works always. Its  janky but thats only way I have been able to get this to work
