### ISSUE TITLE
Bug. Issues with captions

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#165]
https://framatube.org/videos/watch/8519184e-b0c0-45f9-a005-4baddcd41f88

This video has issues with playing captions. First time English captions showed, then I changed resolution but captions vanished and I have been unable to get back captions .

**Comment by test2a** [comment]
this was happening with an instance running 2.4 so i am not sure if 3.0 fixes it.  i will do more tests

**Comment by stom79** [comment]
No I think the bug will remain the same as there are no changes on that point. I will investigate.
