### ISSUE TITLE
"Live not started" warning on working live. 

### ISSUE THREAD

**Issue by Kohoshi12** [stom79/TubeLab#166]
### Issue

The live didn't work on the app, it gave me a "Live not started" warning, even though I could just watch the live on the browser.

### Steps for reproducing the issue
 Enter in a livestream and watch it. The Automatic playback wasn't enabled.

---

Instance: https://peertube.functional.cafe/

- [x] TubeLab
- [ ] TubeAcad

Version of TubeLab: 1.10.2

Android version: 10

**Comment by stom79** [comment]
Yes, it's fixed. You can test the apk here https://framadrive.org/s/A78Kwg86nXdbZMZ
