### ISSUE TITLE
popup mode- unable to go back to app

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#23]
### Issue

pressing home button when video is running pushes video to popup mode fine but we are unable to go back to app. maximize makes video full screen but there, pressing back button goes to popup mode again.

### Steps for reproducing the issue

play video
press home button
video goes to popup mode
click on maximize button on popup
press back button on top
loop.
only way to exit popup mode is to cut popup but app closes.

---

Instance:

- [ x] TubeLab
- [ ] TubeAcad

Version of TubeLab:1.5.2

Android version:8

**Comment by stom79** [comment]
It's fixed. Clicking on the top back button will finish the player activity and go back to main activity.
