### ISSUE TITLE
report video/account

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#25]
### Issue

i am on 1.5.2 and without login but reporting a video says report sent.
report should use peertube reporting menu "and" only allow if logged in first

**Comment by stom79** [comment]
I don't really what to do. Because, the app was refused in the playstore (UGC issue) for not having that button.

**Comment by test2a** [comment]
no. you are doing a great job. i am not asking to not have it. 
instead check the screenshot. 

https://docs.joinpeertube.org/api-rest-reference.html#tag/Abuses/paths/~1abuses/get
this api should help you

![Screenshot_20201105_222602](https://user-images.githubusercontent.com/39449563/98271448-f7b04c80-1fb5-11eb-997a-0ac0a8588cc0.png)

**Comment by stom79** [comment]
I meant for the non authenticated part ;)
Yes, I do use this doc. The abuse report is still a work in progress. I will clearly improve it once introducing first moderator features inside the app.

**Comment by test2a** [comment]
@stom79 yeah. i have tried to reason with the peertube devs about allowing even non logged in users to report but they dont seem to work on it.
then i checked multiple apps, youtube, twitter, facebook also dont let you report without logging in on the website but on the apps you are forced to login so yeah.
reddit is interesting because we can use the android app specifically without logging in and i can find no option to report a post or a comment. i wonder why they are allowed in this case
