### ISSUE TITLE
playlist tab 404 not found

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#28]
### Issue

![Screenshot_20201105-223442](https://user-images.githubusercontent.com/39449563/98272646-53c7a080-1fb7-11eb-95bf-64657f3b6ab0.png)

https://docs.joinpeertube.org/api-rest-reference.html#tag/Video-Playlists/
api reference for playlist handling

---

Instance:

- [x] TubeLab
- [ ] TubeAcad

Version of TubeLab:1.5.2

Android version:

**Comment by stom79** [comment]
Weird. The app fully supports playlists. Can you give a step by step?

**Comment by stom79** [comment]
IMO, it's something on their end. Playlists work fine on other instances.

**Comment by test2a** [comment]
https://imgur.com/a/47pvEah
attached video of the same 
i am facing the same 404 on the upload page and account as well.

**Comment by stom79** [comment]
It's on their end. There is no reasons that these endpoints return 404.

**Comment by test2a** [comment]
> IMO, it's something on their end. Playlists work fine on other instances.

ok. i will try in a different instance.

**Comment by stom79** [comment]
I see they use plugins. Maybe something wrong with one of them.

**Comment by test2a** [comment]
yes. got it. i tried it with a different one and that worked. thanks anyways
