### ISSUE TITLE
unable to view full video description

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#31]
### Issue

currently unable to view full video description and only truncated description is visible.

### Steps for reproducing the issue

---

Instance:

- [x ] TubeLab
- [ ] TubeAcad

Version of TubeLab:1.5.2

Android version:

**Comment by stom79** [comment]
I am enable to reproduce that bug. I checked description when it is seem truncated but I got same results with the web interface. I don't think it's related to the app.

**Comment by test2a** [comment]
okay. did a test. doubled the description of my own video and it seems the app is only displaying the "truncated" preview. web version shows me a "show more" but not in the app

**Comment by test2a** [comment]
![Screenshot_20201107-141120](https://user-images.githubusercontent.com/39449563/98437086-a4e5aa80-2105-11eb-98cb-b7b8f8ce5edf.png)
![Screenshot_20201107-141130](https://user-images.githubusercontent.com/39449563/98437088-a7e09b00-2105-11eb-98f9-e2b034435fdf.png)
![Screenshot_20201107-141139](https://user-images.githubusercontent.com/39449563/98437089-aa42f500-2105-11eb-8f29-37d1845194db.png)
