### ISSUE TITLE
comments have some issues

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#34]
### Issue

1. the comment box looks too big.
2. reddit apps like https://github.com/ccrama/Slide and https://github.com/saket/Dank have really polished the commenting interface. we can  take hints from there. comments are taking too much space right now.

3.  reply to comment if made on website shows up on app correctly but "add a public reply" contains the url of the user which is totally unnecessary. check screenshots.
 
![Screenshot_20201106-235923](https://user-images.githubusercontent.com/39449563/98401920-737cc880-208c-11eb-9b01-74b417a4627e.png)

![Screenshot_20201106-235933](https://user-images.githubusercontent.com/39449563/98401964-85f70200-208c-11eb-997b-18e4f8e65592.png)

4. comments don't show up in the hierarchy  they are made. the web version is still better. 
![Screenshot_20201107_000408](https://user-images.githubusercontent.com/39449563/98402157-d706f600-208c-11eb-9c34-d8744592b417.png)

- [ x] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by stom79** [comment]
4=>I don't understand. For seeing replies, you must click on the sentence "x replies". They are displayed in the order hierarchy returned by the api.

**Comment by test2a** [comment]
@stom79 sorry, i meant identation

**Comment by stom79** [comment]
Currently replies to replies are not idented, but that's endless and impossible to honor on small screens. I will check for a decoration.

**Comment by test2a** [comment]
https://github.com/saket/Dank
you should try this app. it should give you a good implementation of endless comment indentation 

![Screenshot_20201107-125850](https://user-images.githubusercontent.com/39449563/98434825-2d118300-20f9-11eb-9110-f8c768360a49.png)

**Comment by stom79** [comment]
I worked on that. It should be on the next release (indentations for replies, more space to write comments/replies with a dedicated view).

**Comment by test2a** [comment]
@stom79 thats nice to hear. did you fix the username in public reply thing too?
