### ISSUE TITLE
hide watched videos

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#38]
### Issue

reddit apps like slide and many others have a floating buton usually for hiding opened/watched content. this button would help user to discover only new content, and it could be easily disabled 

or, an unobtrusive unwatched icon, red dot or something on unwatched videos. both would be helpful in their own way

- [ x] TubeLab
- [ ] TubeAcad

Version of TubeLab:1.5.2

Android version:

**Comment by stom79** [comment]
That should be a Peertube issue. Dealing with the pagination by removing videos from server replies is really not an easy matter.

**Comment by test2a** [comment]
fair enough. i will close this then. but could you look into unwatched videos having a marker like a "new" or "red dot", it could be device only
