### ISSUE TITLE
Using mastodon account

### ISSUE THREAD

**Issue by lboklin** [stom79/TubeLab#51]
### Issue

I'd like to use my mastodon account to subscribe to, comment on and like videos.

### Steps for reproducing the issue

---

Instance:

- [x] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version: 9 / LineageOS 16.0

**Comment by stom79** [comment]
Work started there: https://github.com/stom79/TubeLab/commits/connect_fediverse_accounts
