### ISSUE TITLE
resolution of videos in numbers

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#52]
### Issue

currently video resolution says 
* high
* medium
* low

can we change this into something like
* 1080p
* 720p
* 480p

this is because it does not say what does high or medium or low means.

### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by stom79** [comment]
I think it's related to #12
