### ISSUE TITLE
weird characters in place of URI

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#56]
### Issue

some videos including the screenshot show weird long numbers in place where usually the username@server is written

![Screenshot_20201108-102842](https://user-images.githubusercontent.com/39449563/98457471-9226b080-21ad-11eb-844d-96275ae9f63c.png)

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by stom79** [comment]
Old channels have this hexadecimal name. I am not sure there are something to do.

**Comment by test2a** [comment]
Okay. Got it. Its from the web itself. Okay. I will close this one
