### ISSUE TITLE
sepia search channel follow button

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#59]
### Issue

i searched for a video in sepia search. in search results, i clicked on a channel but the channel does not show follow button but the video elipses, three dots does show the follow button and allows me to follow a channel.
suggestion, add a follow button just like the button shows up in local videos

![Screenshot_20201108-105844](https://user-images.githubusercontent.com/39449563/98457939-9e147180-21b1-11eb-83dd-0eb9a46fe906.png)

### Steps for reproducing the issue

search in sepia search
select a channel
shows NO follow button
click on video sidebar
click on follow button

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by stom79** [comment]
In fact, that should not even be displayed in the drop-down menu. I have to check if the channel is known by the remote instance before doing that. That's what is done for actions on videos, but I didn't implement yet for channels.

**Comment by test2a** [comment]
is that supposed to be a problem? i have used sepia search to "follow" some accounts and it worked as i "expect" it to. are you saying your local instance needs prior federation with remote instance to allow follow?

**Comment by stom79** [comment]
I meant that depends how admins set their instances. It can fail in some cases. It will also fix the issue with account search.
