### ISSUE TITLE
Pull to refresh with notifications crashes 

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#62]
### Issue

this is continuing from 1.5.2 
liking video crashes the app

### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by stom79** [comment]
I can't reproduce that on my end. Could you tell me your instance?

**Comment by test2a** [comment]
i am using two instances 
https://devtube.dev-wiki.de
tube.ouahpiti.info/
but now like is working fine but not my account. notification pull refresh causes crash on both accounts
![recording-20201110-233211](https://user-images.githubusercontent.com/39449563/98713772-08920100-23ae-11eb-8752-50cce0a3a9db.gif)

**Comment by stom79** [comment]
This one I can reproduce it :)

**Comment by test2a** [comment]
i have had the similar crashes over the past half day now with the new version in mostly the settings pages and the like buttons. i will try to screenrecord if i am able to

**Comment by test2a** [comment]
![recording_20201110_235342](https://user-images.githubusercontent.com/39449563/98715929-cc13d480-23b0-11eb-9c8a-8278d3453612.gif)

**Comment by test2a** [comment]
aha. found one "like' crash. in my videos.
![recording_20201111_000228](https://user-images.githubusercontent.com/39449563/98716834-38430800-23b2-11eb-9642-94d2d4102cf2.gif)
