### ISSUE TITLE
reach owner from channel

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#63]
### Issue

every channel is owned by a user profile and currently we cannot reach the owner page from a channel. newpipe correctly displays the channel and allows reaching the owner page as "created by"

### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:1.6.0

Android version:

**Comment by stom79** [comment]
Yes, even myself I am missing that feature :)

**Comment by test2a** [comment]
tubelab and newpipe same channel

![Screenshot_20201110-234036](https://user-images.githubusercontent.com/39449563/98715088-ad610e00-23af-11eb-8a04-1a1645dbdb6b.png)
![Screenshot_20201110-234043](https://user-images.githubusercontent.com/39449563/98715098-b0f49500-23af-11eb-847e-eefe546a194d.png)
![Screenshot_20201110-234047](https://user-images.githubusercontent.com/39449563/98715226-dd101600-23af-11eb-8c63-23402e187a67.png)

**Comment by stom79** [comment]
With peertube, it is no longer possible to follow accounts. IMO, it's better to indicate "follow all channels" of the account.

**Comment by test2a** [comment]
Yes. And isnt that the same thing? So say subscribe to all channels.

**Comment by test2a** [comment]
also how about a tab in a user page to show what channels that user has?
