### ISSUE TITLE
Suffix in url

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#70]
https://ibb.co/PhgzHY6

Check the recording.

I tried to login to an instance
peertube2.Cpy.re with a random user login.
It correctly says invalid password and such.

The problem is if I write peertube2.cpy.re/
because from the desktop the ending slash is copied, it says client id wrong. This is similar to how https:// prefix you corrected last time

**Comment by stom79** [comment]
OK. I didn't test ending only with a slash without protocol.
