### ISSUE TITLE
resolution does not seem to change

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#73]
### Issue

this is a difficult to explain but it seems the video resolution selector is not doing anything. i checked this with a video with lots of text and changing resolution did nothing to change text on screen. i was only able to change using the settings "default" high or medium. then the video quality did improve or decrease. low is essentially unplayable and this is how i found the current bug. if by whatever reason, 0p is selected, no video should come. but changing resolution should get video but the video was only playing in 0p suggesting resolution selector on video page is not doing its job

### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by stom79** [comment]
That was a bug that I fixed recently. The low selector did have an issue if a 0p resolution was present (because it was automatically selected).

I will check what happens when changing the resolution.

**Comment by test2a** [comment]
currently the resolution selector does nothing to improve or reduce quality of the video as it should.

**Comment by test2a** [comment]
i think we should close this as its mostly fixed.
