### ISSUE TITLE
subscriptions issue

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#80]
### Issue

i subscribed to thelinuxexperiment_channel@tilvids.com from sepia search i think. anyways, the same is showing in the subscriptions tab properly but when i click on the icon at top, or view the profile, it shows no videos but clearly there are public videos which play on desktop fine but not in the app

https://tube.ouahpiti.info/videos/watch/0718044b-95a5-4117-958b-ecec5d218091 link to a video which i am able to play on desktop
https://tube.ouahpiti.info/video-channels/thelinuxexperiment_channel@tilvids.com/videos link to the remote channel on my instance
i also checked a video which i think is local to the instance from subscriptions tab and that works perfectly

![recording_20201116_211651](https://user-images.githubusercontent.com/39449563/99275928-18985d80-2852-11eb-8ba8-c7fbaf7a2e90.gif)

### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by stom79** [comment]
I guess your instance doesn't follow the targeted one. It's what I told previously with the follow button. I need to check if when a new video is published the account received metadata from the remote instance.
But it's not a bug from the app.
