### ISSUE TITLE
video upload error

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#95]
### Issue

oops. an error occured. a notification comes.
unable to upload any videos from phone.

also, the default name should be picked up same as website does. we can later change but website auto selects default name.
dont know if the description and details are to be added right after upload as i could never finish it

### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by stom79** [comment]
For this bug, I should have logs otherwise it's impossible to know why it failed.

**Comment by test2a** [comment]
Is there a debug log in the app I can share?

**Comment by test2a** [comment]
ok. i used two instances one on 2.4 and 2.3 and both failed to upload
