### ISSUE TITLE
comments can be better

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#96]
### Issue

from the start, comments are so much better than they were back in 1.5 but there is still scope of improvement.. i am not asking to have this fixed on priority or anything. just how it can be better in the long run
* there is no visual separation between where video ends and comments start except from the text "enter a public comment"

![Screenshot_20201118-225145](https://user-images.githubusercontent.com/39449563/99564753-d5c0bc00-29f0-11eb-9158-8db7ac6ff7c3.png)

here i have attached screenshot of reddit app slide which has a simple "reply" icon. everyone knows what it is and what it does. also, there is a black separation between above text and comments below
![Screenshot_20201118-225350](https://user-images.githubusercontent.com/39449563/99565042-351ecc00-29f1-11eb-8e5a-e41d7b7219f8.png)

* secondly, icon thumbnails take up too much space and most people dont set their profile picture so its just a wall of smiley faces. this one is debatable and i wouldnt mind it much if it stays or whatever.

* thirdly, allow right swipe to close comment window. right now there is a small x at top that needs to be clicked if we are in a comment.

* fourth, allow full page comment writing. the text box while big is no match to using your full screen to type. that way you can write a lot more and scroll up or down in the text.

* fifth, unable to view comments in landscape mode. the video player twists and turns around, fullscreen and back

### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by test2a** [comment]
when viewing comments, can we not fix the video player to the top portion of the screen? comments are an integral part of the experience and if i want to scroll down, meaning i want to only read comments, the full screen should be at my disposal and not half because the top half is used by video player

**Comment by test2a** [comment]
![Screenshot_20201119-101721](https://user-images.githubusercontent.com/39449563/99622654-9a55da00-2a50-11eb-88ab-e4a084a79172.png)
instead of writing "1 reply" or "3 replies" this app uses a icon with a number to indicate the same thing. clicking on that comment shows those ones and clicking again hides it. kinda like how tubelab does the "click on 1 reply" and new page shows up. this just looks cleaner and see how comments are separated

**Comment by test2a** [comment]
do we really need to show the userid of the commenter ? its not like we need to do any actions, if we "reply" to anyone, their userid already shows up. it just clutters the UI with unnecessary information that is not important

**Comment by test2a** [comment]
Comments on desktops have a threadid when you click on the time. You can use this to reach a particular comment. We should be able to get a comment URL and share that. Same for clicking a link containing threadid and reaching that thread

**Comment by test2a** [comment]
Interesting observation. Any comment thread longer than 6 is just put together in one line instead of further indentation.
I tested with a video and made a comment and relied to that comment and so on.
On the web version I can see around 15 replies in a tree while in app, indentation works till 6 replies. After that, they get same indentation of 6th comment.

Will send a screenshot.

Also, you reduced indentation to 10. From 15. I suggest go to 5 or lower because that way more comments can be fitted in screen.

**Comment by stom79** [comment]
Yes, I voluntary stopped indentation after a number of sub-reply.

**Comment by test2a** [comment]
Can we have collapsable comments? That would solve this issue somewhat
