### ISSUE TITLE
[bug] fullscreen shows status bar

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#99]
### Issue

i am unable to hide the status bar when in fullscreen. the  visibility of status bar should be linked to the overlay that shows up if we do a forward/backward/pause gesture or click on cog wheel. otherwise the display should just show the video.
![Screenshot_20201119-140205](https://user-images.githubusercontent.com/39449563/99641280-0f84d780-2a70-11eb-898d-922d77e8292d.png)
 

### Steps for reproducing the issue

---

Instance:

- [ ] TubeLab
- [ ] TubeAcad

Version of TubeLab:

Android version:

**Comment by stom79** [comment]
I can't reproduce that on my end.

**Comment by stom79** [comment]
Do you still have this issue?

**Comment by test2a** [comment]
Yep.

**Comment by test2a** [comment]
![Screenshot_20201124-223503](https://user-images.githubusercontent.com/39449563/100127944-a2c17100-2ea5-11eb-8fd1-d3f81fe2ce0d.png)

**Comment by stom79** [comment]
Is a recent bug? Because I changed this part few releases ago.

**Comment by test2a** [comment]
Wait. I will download an older version like 1.5 and confirm

**Comment by test2a** [comment]
Yes. 1.5 from f droid does not show the status bar

**Comment by stom79** [comment]
OK. That will be an easy fix. Thanks for tests
